### ISSUE TITLE
How to observe the taint locations and/or count tainted number of bits during simulation?

### ISSUE THREAD

**Issue by sammy17** [comsec-group/cellift-meta#1]
First, thank you for open-sourcing all the work in a detailed manner! 

I had one question related to observing taint propagation.  I got Pulpisimmo working with Verilator and CellIFT instrumentation and I can run the simulation with the given tests (bugs). 
How can I monitor the taint propagation or measure the number of tainted bits as the simulation progress? 

I did not see this info in the documentation.

**Comment by flaviens** [comment]
Hi @sammy17,
My apologies, I missed your message, I forgot to click the `watch` button on this repository ^^'

Essentially, as you probably understood from the paper, all usual state elements get doubled, the new element being the `shadow` aka `taint` register, whose name is basically the name of the register concatenated with `_t0`.
We implemented the `list_state_elements` pass in `cellift-yosys` to list the registers. From there, you can monitor these registers, for example, by looking at their values for each cycle in simulation.
Hope it helps!
